<?php

$this->setup(array(
    'title' => 'Championship settings',
    'panel' => 'centered-panel',
    'back' => array(
        'Championship-Administration' => $this->url('backend/championship'),
    ),
));

?>

<div>
    <h1><?= $this->t('Championship settings') ?></h1>

    <div class="separator-small"></div>

    <div class="padded">
        <?php

        $form = $this->configForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('backend/championship/config'));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <table class="default-table">
            <?= $this->formRowCheckbox($form, 'ccf-enabled') ?>

            <tr>
                <td>&nbsp;</td>

                <td>
                    <?= $this->formElement($form->get('ccf-submit')) ?>
                </td>
            </tr>
        </table>

        <?= $this->form()->closeTag() ?>
    </div>
</div>
