<?php

$cid = $this->championship->need('cid');

$backUrl = $this->url('backend/championship/edit', ['cid' => $cid]);

$this->setup(array(
    'title' => 'Delete this championship',
    'panel' => 'centered-panel',
    'back' => array(
        'Championship' => $backUrl,
    ),
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to delete this championship?') ?></span></p>

    <p><?= $this->t('This also deletes all its categories, registrations, groups and matches.') ?></p>

    <p class="no-wrap">
        <a href="<?= $this->url('backend/championship/delete', ['cid' => $cid], ['query' => ['confirmed' => 'true']]) ?>" class="default-button">
            <span class="symbolic symbolic-cross"><?= $this->t('Yes, delete this championship') ?></span>
        </a>

        &nbsp;

        <a href="<?= $backUrl ?>" class="default-button"><?= $this->t('No, go back') ?></a>
    </p>
</div>
