<?php

$catid = $this->group->need('catid');

$backUrl = $this->url('backend/championship/category-edit', ['catid' => $catid]);

$this->setup(array(
    'title' => 'Delete this group',
    'panel' => 'centered-panel',
    'back' => array(
        'Category' => $backUrl,
    ),
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to delete this group?') ?></span></p>

    <p><?= $this->t('This also deletes all its matches.') ?></p>

    <p class="no-wrap">
        <a href="<?= $this->url('backend/championship/group-delete', ['gid' => $this->group->need('gid')], ['query' => ['confirmed' => 'true']]) ?>" class="default-button">
            <span class="symbolic symbolic-cross"><?= $this->t('Yes, delete this group') ?></span>
        </a>

        &nbsp;

        <a href="<?= $backUrl ?>" class="default-button"><?= $this->t('No, go back') ?></a>
    </p>
</div>
