<?php

if ($this->group) {
    $gid = $this->group->need('gid');
} else {
    $gid = null;
}

$catid = $this->category->need('catid');

$this->setup(array(
    'title' => 'Championship-Administration',
    'panel' => 'centered-panel large-sized',
    'back' => array(
        'Category' => $this->url('backend/championship/category-edit', ['catid' => $catid]),
    ),
));

?>

<?= $this->partial('championship/partial/table-style.phtml') ?>

<div>
    <h1><?= $this->t('Group') ?>: <?= $this->escapeHtml($this->category->need('name')) ?></h1>

    <div class="separator-small"></div>

    <div class="padded">
        <?php

        $form = $this->groupForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('backend/championship/group-edit', ['gid' => $gid], ['query' => ['catid' => $catid]]));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <div style="overflow-x: auto;">
            <table class="default-table championship-table">
                <?= $this->formRowDefault($form, 'gf-name') ?>

                <tr>
                    <td class="default-form-label-row">
                        <?= $this->formLabel($form->get('gf-members')) ?>
                        <br>
                        <span class="gray"><?= sprintf($this->t('Max. %d members'), $this->category->get('group_size_max', 6)) ?></span>
                    </td>
                    <td>
                        <?php $this->formMultiCheckbox()->setSeparator('<br>'); ?>
                        <?= $this->formMultiCheckbox($form->get('gf-members')) ?>

                        <?= $this->formElementErrors($form->get('gf-members')) ?>
                        <?= $this->formElementNotes($form->get('gf-members')) ?>

                        <?php if (! $form->get('gf-members')->getValueOptions()): ?>
                            <p class="gray"><?= $this->t('No unassigned participants are left for this category.') ?></p>
                        <?php endif; ?>
                    </td>
                </tr>

                <tr>
                    <td>&nbsp;</td>

                    <td>
                        <?= $this->formElement($form->get('gf-submit')) ?>

                        <?php if ($this->group): ?>
                            <span class="gray" style="margin: 0 8px;"><?= $this->t('or') ?></span>

                            <a href="<?= $this->url('backend/championship/group-delete', ['gid' => $gid]) ?>" class="default-button">
                                <span class="symbolic symbolic-cross"><?= $this->t('Delete') ?></span>
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            </table>
        </div>

        <?= $this->form()->closeTag() ?>
    </div>
</div>
